In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [6]:
treino_nr = pd.read_csv("../data/interim/titanic_numerical.csv")
testes_nr = pd.read_csv("../data/interim/titanic_testes_numerical.csv")
treino_nr.head()

   pclass  survived      age  sibsp  parch      fare
0       1         1  29.0000      0      0  211.3375
1       1         1   0.9167      1      2  151.5500
2       1         0   2.0000      1      2  151.5500
3       1         0  30.0000      1      2  151.5500
4       1         0  25.0000      1      2  151.5500

In [7]:
testes_nr.head()

   passengerid  pclass   age  sibsp  parch     fare
0          892       3  34.5      0      0   7.8292
1          893       3  47.0      1      0   7.0000
2          894       2  62.0      0      0   9.6875
3          895       3  27.0      0      0   8.6625
4          896       3  22.0      1      1  12.2875