In [45]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [46]:
treino_nr = pd.read_csv("../data/interim/titanic_numerical.csv")
testes_nr = pd.read_csv("../data/interim/titanic_testes_numerical.csv")
treino_nr.head()

   passengerid  survived  pclass   age  sibsp  parch     fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [47]:
testes_nr.head()

   passengerid  pclass   age  sibsp  parch     fare
0          892       3  34.5      0      0   7.8292
1          893       3  47.0      1      0   7.0000
2          894       2  62.0      0      0   9.6875
3          895       3  27.0      0      0   8.6625
4          896       3  22.0      1      1  12.2875

In [48]:
X = treino_nr.drop(["passengerid","survived"], axis=1)
y = treino_nr["survived"]

In [49]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [50]:
from sklearn import tree
clf = tree.DecisionTreeClassifier( random_state=42)

In [51]:
clf = clf.fit(X_train, y_train)

In [52]:
y_pred = clf.predict(X_val)

In [53]:
accuracy_score(y_val, y_pred)

0.6424581005586593

In [54]:
confusion_matrix(y_val, y_pred)

array([[79, 26],
       [38, 36]])